# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: windows-2022
    env:
      Debug_Build_Path: bin/Debug/net8.0/
      Release_Build_Path: bin/Release/net8.0/win-x64/publish/

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.X
        # cache: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Debug Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Release Build
      run: dotnet publish
    - name: Upload build artifacts1
      uses: actions/upload-artifact@v4
      with:
        name: debugBuild
        path: ${{ env.Debug_Build_Path }}
    - name: Upload build artifacts2
      uses: actions/upload-artifact@v4
      with:
        name: releaseBuild
        path: ${{ env.Release_Build_Path }}